# file: test/_manual/user_profile.http

POST http://localhost:5000/api/auth/login
content-type: application/json

{
    "username": "user-1@example.com",
    "password": "newtest"
}

###

GET http://localhost:5000/api/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5NzkzNDU3OSwianRpIjoiMjdiOGFkZjAtMzFmNi00MjliLWIxNGUtNmQ0NWEyNTA2ZDFhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InVzZXItMSIsIm5iZiI6MTY5NzkzNDU3OSwiZXhwIjoxNjk3OTQxNzc5fQ.OPhOfBChiFRPcSVuLgtOAFS7WXgB7XH0udqSIAsa9JI
